Fix: check if error is a String before we throw, Dart doesn't have a top-level class for Exceptions*
Well, it does have Exception class, but NoSuchMethodError, for example, doesn't inherit from it.
Thus we better check that what we've captured is a String and if it's not - we can throw.